# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7a09f92e5ac3e2dfc2317edcb4a92f5cc70192ea47f6c76a6929a03aca005fccd638467fa4b8f53fe467998a9769e40d4fbc72937df1033c78b87a458161c3f

test:
  secret_key_base: d1c471a2602cb52755a2288e19fba851a2761c13197ab66af19d691a60f303581c5ee85414426e94346a1e788b713ff8b5235807a16725d12c67d739a594c2d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
